### ISSUE TITLE
Steps out of order bug - ice gloves in inv but telling me to withdraw

### ISSUE THREAD

**Issue by BWPearson** [Toofifty/easy-blastfurnace#11]
If you log out after withdrawing ore but before putting it on the conveyor, log back in, when you attempt a new cycle it will be out of order, prompting you to withdraw your ice gloves when they are in your inventory next time you visit the bank to drop off your bars, and everytime after that. reinstalling does not fix this issue
![image](https://user-images.githubusercontent.com/23534932/188034848-70b22777-dbe6-4b17-8d40-e2bd107b4722.png)

**Comment by hugocowan** [comment]
Yep, my bad. I've made a pull request to fix this.
