### ISSUE TITLE
Coal bag content overlay gets toggled empty after placing coal ores onto conveyor belt

### ISSUE THREAD

**Issue by adamhirzalla** [Toofifty/easy-blastfurnace#18]
Not sure if it's just on my side (can provide my shift/left click runelite configs if needed), but whenever I have a filled coal bag (27 ores) and a full inventory of coal ores (27 ores), placing my **inventory** ores onto the belt (without emptying my coal bag) causes the bag overlay to show 0 when it's still filled. I even get instructed to head back to bank, skipping emptying + placing my coals from the bag.

It behaves fine when having a full coal bag + other types of ores in my inventory. It only happens when it's a full coal bag + full inventory of coal. I'm assuming placing coal ores onto the belt toggles the bag empty (rather than actually emptying the coal bag)

Sweet Plugin!

**Comment by hugocowan** [comment]
@adamhirzalla @Toofifty I've made a fix and submitted a pull request for it: https://github.com/Toofifty/easy-blastfurnace/pull/19

It's a case that should be accounted for, I missed it in testing. Thanks for reporting, it's a really helpful find! Do let me know if there are still issues once the changes make it to Runelite.

**Comment by hugocowan** [comment]
@adamhirzalla This issue is now fixed in runelite. Please do report back with another issue if it is still a problem for you.

**Comment by hugocowan** [comment]
@Toofifty Looks like it's safe to close this one
