### ISSUE TITLE
Stamina problem

### ISSUE THREAD

**Issue by Kas3m** [Toofifty/easy-blastfurnace#23]
Hello, thanks for your great effort you put in this plugin but since last update there is a minor issue
the stamina potion management isn't working what ever you set it to it never asks you to drink stamina potion
it also doesnt change the method to another method when you change ores like if you are using gold + addy method then you want to change to gold + rune it doesnt change by pulling the ores out of the bank you have to leave the area and come back
thanks again for your efforts

**Comment by scoggin949** [comment]
Also having stamina issue. Otherwise a really great plugin!!

**Comment by hugocowan** [comment]
ohboy okay. I'll take a look into this, only just saw it now. Happy New Year and such

**Comment by hugocowan** [comment]
Stamina management fix has been made, it just needs @Toofifty to merge it into master and then submit it to the plugin hub.

**Comment by Kas3m** [comment]
happy new year to you bro and thanks for all your efforts to maintain this and keep it going really appreciate it
have a great time and a great year
