### ISSUE TITLE
wrong coal bag quantity when emptying and filling on the same tick

### ISSUE THREAD

**Issue by DSatanove** [Toofifty/easy-blastfurnace#27]
In metal + gold methods, you have to empty 1 coal from the coal bag before filling it when at the bank. With menu entry swapper, you can double click the coal bag to 'empty' and 'fill' on the same tick. However when you do that the plugin doesn't track the second 'fill' click and says that the coal bag has 0 coal in it.

**Comment by hugocowan** [comment]
Interesting, I don't think I'd ever tried one-ticking the coal bag to empty/fill it.

You can use the menu entry swapper to have the coal bag fill on left click when in the bank screen, and empty on left click when out of it. Saves you a click and side-steps this issue.

Saying that, I'll take a look and see what I can do to stop this sort of thing happening. Might not be possible.
